// Dailymotion Player Embed v-0.0.3619-rc1
// This file is generated dynamically, do not host it yourself
// Statically hosting or caching this file will break your integration
'use strict';var _dmpesplayer=function(){function ea(){return(new URL(window.location.href)).searchParams.get("dmLogger")||""}function fa(a,b){if(Da&&console[b]){for(var c=arguments.length,d=Array(2<c?c-2:0),f=2;f<c;f++)d[f-2]=arguments[f];c=[`%cPES%c${a}`,"border-radius: 0.125rem; padding: 0.0625rem 0.1875rem; margin: 0 0.0625rem; color: white;; background: purple","border-radius: 0.125rem; padding: 0.0625rem 0.1875rem; margin: 0 0.0625rem; color: white;; background: #ae27ae",...d];console[b](...c)}}
function Ea(){let a=null;if(A())return m.log("Skipping 3rd party cookie detection on dailymotion.com"),Promise.resolve();let b=new Promise(d=>{a=setTimeout(()=>{m.log("3rd party cookie","Received detection timeout");return d()},2E3)}),c=new Promise(d=>{if(A())return m.log("Skipping 3rd party cookie detection on dailymotion.com"),d();const f=document.createElement("script");f.src=`${J()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"}/cookie.js`;f.onload=()=>{m.log("3rd party cookie",
"Script loaded");clearTimeout(a);return d()};f.onerror=()=>{m.log("3rd party cookie","Script error");clearTimeout(a);return d()};document.head.appendChild(f)});return Promise.race([c,b])}let ha=a=>new Promise((b,c)=>{const d=a.getAttribute("load-status");if("loaded"===d)return b();if("error"===d)return c();a.addEventListener("load",()=>{a.setAttribute("load-status","loaded");b()});a.addEventListener("error",()=>{a.setAttribute("load-status","error");c()})}),B={"udger":{"browserOsFamily":"Windows","browserOsName":"Windows 10","browserUaFamily":"Firefox","browserUaName":"Firefox 128.0","browserUaVersion":128,"deviceType":"desktop"},"geoip":{"visitorAsNumber":"AS61461","visitorCity":"Coro","visitorContinent":"SA","visitorCountry":"VE","visitorRegion":"I"},"playerEnv":"prod","playerGatekeepers":["PV5_ADSENSE_DISPLAY_PREROLL","PV5_AD_BUFFET","PV5_AD_COOKIE_SYNC","PV5_AUDIO_ADS_POC","PV5_COOKIE_SYNC_AB_TEST","PV5_ENABLE_IMA_OMSDK","PV5_IAS_INAPP","PV5_IGNORE_EARLY_LOAD_MIDROLL","PV5_IMA_NATIVE_POC","PV5_IMA_OVERLAY","PV5_LIVE_MIDROLL_DISABLED","PV5_MULTI_FALLBACK","PV5_OMSDK","PV5_OMSDK_NATIVE","PV5_PROXY_LOAD_POSTROLL","PV5_SAVE_VAST_RECORD","PV5_TEMP_IMA_PAGEURL","PV5_TEMP_IMA_PAGEURL_OFFSITE","PV5_WATCHTOWER","PV5_SIMID","PV5_MIDROLL_RETAKE_ONSITE","PV5_MIDROLL_RETAKE_OFFSITE","PV5_V2V_ONSITE_QUERY","PV5_ADS_ON_REPLAY_ONSITE","PV5_ADS_ON_REPLAY_OFFSITE","PV5_IMA_COMPANION_AD","PV5_INFOPACK_ENABLED_ONSITE"],"trafficSegment":795299,"v1st":"4a0c7f35-949a-4d58-9787-6a6bd61757da","player":{"id":"xjsl5","ownerId":"x1nd5m8","status":"ok","aspectRatio":"16:9","autoskipAfter":30,"autostart":"off","color":"","contextualContentSource":"channel","enableAdsAutopauseInactiveTab":false,"enableAdsControls":true,"enableAutomaticRecommendations":false,"enableAutonext":false,"enableAutoskip":false,"enableChannelLink":true,"enableClickToUnmute":true,"enableContextualContent":false,"enableCustomRecommendations":false,"enableDmLogo":true,"enableGooglePolicyUi":false,"enableInfo":false,"enableLiveOffairScreen":true,"enablePlaybackControls":true,"enableReceiveUrlLocation":true,"enableSharing":true,"enableSharingUrlLocation":false,"enableStartPipExpanded":false,"enableStartscreenDmLink":true,"enableSubtitles":true,"enableTapToUnmute":true,"enableTitlesInVideoCards":true,"enableVideoTitleLink":true,"enableWaitForCustomConfig":true,"hasAds":true,"hasReachedPlaybackLimits":false,"hasSsai":false,"pip":"off","recommendationsOptimisation":"engagement","watermarkImageType":"none","watermarkImageUrl":"","watermarkLinkType":"none","watermarkLinkUrl":""}},ia=[{key:"id",isPublic:!0,
isTrackable:!0},{key:"ownerId",isPublic:!1,isTrackable:!1},{key:"status",isPublic:!1,isTrackable:!1},{key:"aspectRatio",isPublic:!0,isTrackable:!0},{key:"autoskipAfter",isPublic:!0,isTrackable:!0},{key:"autostart",isPublic:!0,isTrackable:!0},{key:"color",isPublic:!0,isTrackable:!0},{key:"contextualContentSource",isPublic:!0,isTrackable:!0},{key:"enableAdsAutopauseInactiveTab",isPublic:!1,isTrackable:!0},{key:"enableAdsControls",isPublic:!0,isTrackable:!0},{key:"enableAutomaticRecommendations",isPublic:!0,
isTrackable:!0},{key:"enableAutonext",isPublic:!0,isTrackable:!0},{key:"enableAutoskip",isPublic:!0,isTrackable:!0},{key:"enableChannelLink",isPublic:!0,isTrackable:!0},{key:"enableClickToUnmute",isPublic:!0,isTrackable:!0},{key:"enableContextualContent",isPublic:!0,isTrackable:!0},{key:"enableCustomRecommendations",isPublic:!0,isTrackable:!0},{key:"enableDmLogo",isPublic:!0,isTrackable:!0},{key:"enableGooglePolicyUi",isPublic:!0,isTrackable:!0},{key:"enableInfo",isPublic:!0,isTrackable:!0},{key:"enableLiveOffairScreen",
isPublic:!0,isTrackable:!0},{key:"enablePlaybackControls",isPublic:!0,isTrackable:!0},{key:"enableReceiveUrlLocation",isPublic:!0,isTrackable:!0},{key:"enableSharing",isPublic:!0,isTrackable:!0},{key:"enableSharingUrlLocation",isPublic:!0,isTrackable:!0},{key:"enableStartPipExpanded",isPublic:!0,isTrackable:!0},{key:"enableStartscreenDmLink",isPublic:!0,isTrackable:!0},{key:"enableTapToUnmute",isPublic:!0,isTrackable:!0},{key:"enableTitlesInVideoCards",isPublic:!0,isTrackable:!0},{key:"enableVideoTitleLink",
isPublic:!0,isTrackable:!0},{key:"enableWaitForCustomConfig",isPublic:!0,isTrackable:!0},{key:"hasAds",isPublic:!1,isTrackable:!0},{key:"hasReachedPlaybackLimits",isPublic:!1,isTrackable:!0},{key:"hasSsai",isPublic:!1,isTrackable:!0},{key:"pip",isPublic:!0,isTrackable:!0},{key:"recommendationsOptimisation",isPublic:!0,isTrackable:!0},{key:"watermarkImageType",isPublic:!0,isTrackable:!0},{key:"watermarkImageUrl",isPublic:!0,isTrackable:!1},{key:"watermarkLinkType",isPublic:!0,isTrackable:!0},{key:"watermarkLinkUrl",
isPublic:!0,isTrackable:!1}],V=a=>{var b;return null===(b=B.playerGatekeepers)||void 0===b?void 0:b.includes(a)},J=()=>{var a,b;return(null===(a=window.dailymotion)||void 0===a?0:null===(b=a._do_not_use_d4e7ed1124e1417cdb42)||void 0===b?0:b.isGeo2)||V("PV5_USE_GEO2_IFRAME")||V("PV5_USE_GEO2_IFRAME_APAC")?!0:!1},W=(a,b)=>{const c={};ia.filter(d=>d[b]).forEach(d=>{({key:d}=d);c[d]=a[d]});return c},Fa=function(a){let b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};b&&"object"===typeof b&&
Object.keys(b).forEach(c=>{ia.map(d=>{({key:d}=d);return d}).includes(c)&&A()&&(a[c]=b[c],a.hasOverride=!0)});return a},ja=a=>"string"===typeof a?Ga(a):a,Ga=a=>{const b={};a.split("&").forEach(c=>{const [d,f]=c.split("=");d&&f&&(c=d.match(/([a-zA-Z0-9]+)\[([a-zA-Z0-9]+)\]/),"true"===f?b[d]=!0:"false"===f?b[d]=!1:f.match(/^[0-9]+$/)?b[d]=d.match(/color$/i)?f:parseInt(f):c?b[c[1]]={...b[c[1]],[c[2]]:decodeURIComponent(f)}:b[d]=decodeURIComponent(f))});return b},A=()=>(window.location.hostname||window.origin).endsWith(".dailymotion.com"),
ka=(a,b,c,d)=>{a.addEventListener(b,c,d);return()=>{a.removeEventListener(b,c,d)}},N=function(a,b){document.cookie=[`${a}=${b}`,"path=/",`max-age=${2<arguments.length&&void 0!==arguments[2]?arguments[2]:31536E6}`,"samesite=lax;secure"].join(";")},O=a=>{const b=window.document.cookie.split(";").map(c=>c.trim()).find(c=>c.startsWith(a));return(null===b||void 0===b?void 0:b.split("=")[1])||""},P=()=>{const a=[],b=new window.Uint16Array(32);window.crypto.getRandomValues(b);b.forEach(c=>a.push(`000${c.toString(16)}`.slice(-4)));
return`${a[0]}${a[1]}-${a[2]}-${a[3]}-${a[4]}-${a[5]}${a[6]}${a[7]}`},t={PUBLIC:{AD_CLICK:"ad_click",AD_COMPANIONSREADY:"ad_companions",AD_DURATIONCHANGE:"ad_durationchange",AD_END:"ad_end",AD_ERROR:"ad_error",AD_IMPRESSION:"ad_impression",AD_LOADED:"ad_loaded",AD_PAUSE:"ad_pause",AD_PLAY:"ad_play",AD_READYTOFETCH:"ad_readytofetch",AD_START:"ad_start",AD_TIMECHANGE:"ad_timeupdate",PLAYER_ASPECTRATIOCHANGE:"pes_aspectratiochange",PLAYER_CRITICALPATHREADY:"playback_ready",PLAYER_END:"end",PLAYER_ERROR:"error",
PLAYER_HEAVYADSINTERVENTION:"player_heavyadsintervention",PLAYER_PIPEXPANDEDCHANGE:"pes_pipexpandedchange",PLAYER_PLAYBACKPERMISSION:"playback_resolution",PLAYER_PLAYBACKSPEEDCHANGE:"playbackspeedchange",PLAYER_PRESENTATIONMODECHANGE:"pes_presentationmodechange",PLAYER_RECODISPLAY:"recodisplay",PLAYER_SCALEMODECHANGE:"pes_scalemodechange",PLAYER_START:"start",PLAYER_VIDEOCHANGE:"videochange",PLAYER_VIDEOLISTCHANGE:"videolistchange",PLAYER_VIEWABILITYCHANGE:"pes_viewabilitychange",PLAYER_VOLUMECHANGE:"volumechange",
VIDEO_BUFFERING:"waiting",VIDEO_DURATIONCHANGE:"video_durationchange",VIDEO_END:"video_end",VIDEO_PAUSE:"pause",VIDEO_PLAY:"play",VIDEO_PLAYING:"playing",VIDEO_PROGRESS:"progress",VIDEO_QUALITIESREADY:"qualitiesavailable",VIDEO_QUALITYCHANGE:"qualitychange",VIDEO_SEEKEND:"seeked",VIDEO_SEEKSTART:"seeking",VIDEO_START:"video_start",VIDEO_SUBTITLESCHANGE:"subtitlechange",VIDEO_SUBTITLESREADY:"subtitlesavailable",VIDEO_TIMECHANGE:"timeupdate"},PRIVATE:{ALL:"all",BACK_TO_INLINE_DISPLAY_REQUESTED:"pes_pip_back_to_inline_display_requested",
CLOSE_PIP_REQUESTED:"pes_pip_close_requested",COLLAPSE_PIP_REQUESTED:"pes_pip_collapse_requested",DISPLAY_POSTER_SOONER:"poster_sooner",EXPAND_PIP_REQUESTED:"pes_pip_expand_requested",PLAYER_APIREADY:"apiready",PLAYER_FULLSCREENCHANGE:"fullscreenchange",PLAYER_NATIVEPIPCHANGE:"presentationmodechange",PLAYER_STATE:"playerstate",WRITE_UID:"pes_write_uid"}},q={CUSTOMCONFIG:"set-ads-config",FULLSCREEN:"fullscreen",INIT_PIP_IFRAME_CHUNK:"initPesPipChunk",LOAD:"load",LOOP:"loop",MUTED:"muted",NOTIFY_EMBEDDER_URL_CHANGED:"notifyEmbedderURLChanged",
NOTIFY_PIP_CHANGED:"notifyPesPipChanged",PAUSE:"pause",PLAY:"play",QUALITY:"quality",PLAYER_VISIBILITY:"notifyPesPlayerVisibility",SCALE:"scaleMode",SEEK:"seek",SPEED:"speed",STATE:"playerstate",SUBTITLES:"subtitle",UPDATE_NEON_TRACKING_DATA:"updateNeonTrackingData",UPDATE_PARAMS:"updatePesParams",VIEWPORT_RESIZE:"notifyPesViewportSizeChanged",VOLUME:"volume",CONTROLS:"controls",CUSTOM_RECOMMENDATIONS:"customRecommendations"},X=a=>Object.values(t.PUBLIC).includes(a),r=function(a,b){for(var c,d,f=
arguments.length,h=Array(2<f?f-2:0),g=2;g<f;g++)h[g-2]=arguments[g];null===(c=a._do_not_use_d4e7ed1124e1417cdb42.iframe)||void 0===c?void 0:null===(d=c.contentWindow)||void 0===d?void 0:d.postMessage(JSON.stringify({command:b,parameters:h}),J()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com")},K=(a,b)=>{window.postMessage(JSON.stringify({event:a,...b}),window.origin)},C=(a,b,c)=>la(a,b,c),ma=(a,b)=>la(null,a,b),la=(a,b,c)=>ka(window,"message",d=>{let {origin:f,data:h}=d;if((f===window.origin||
f===(J()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"))&&h&&"string"===typeof h)try{const g=JSON.parse(h);"all"!==b&&b!==g.event||null!==a&&a._do_not_use_d4e7ed1124e1417cdb42.id!==g.id||c(g)}catch(g){}}),Da=ea().split(",").includes("pes"),m={log:function(a){for(var b=arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];return fa(a,"log",...c)},error:function(a){for(var b=arguments.length,c=Array(1<b?b-1:0),d=1;d<b;d++)c[d-1]=arguments[d];return fa(a,"error",...c)}},
Ia=async()=>{var a=await Ha(),b;a:{var c=["h1","h2","h3","title"];for(const d of c)if(c=null===(b=document.querySelector(d))||void 0===b?void 0:b.textContent.trim(),"string"===typeof c&&0<c.length){b=c.substring(0,2E3);break a}b=""}a={content:a,title:b,url:window.location.href};m.log("Contextual embed","Extracted data:",a);return a},Ha=async()=>{await new Promise(b=>setTimeout(b,10));let a=document.querySelector("body").innerText;a=a.replace(/\n/g," ");return a.substring(0,8E3)},L=!1,Q=!1,na=new RegExp(/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}/),
Y=null,Ja=()=>{const a=O("uid_dm");return null===a||void 0===a?void 0:a.match(na)},Ka=()=>{var a;!1!==(null===(a=B.player)||void 0===a?void 0:a.hasAds)&&(a=O("uid_dm"),Y=(null===a||void 0===a?0:a.match(na))?a:P())},La=new RegExp(/^[a-zA-Z0-9-]+$/),H=null,Ma=()=>{const a=Q,b=O("v1st_dm");a?(m.log("Config","Got v1st from backend, 3rd party cookie allowed"),H=B.v1st):(null===b||void 0===b?0:b.match(La))?(m.log("Config",'Got v1st from 1st party cookie "v1st_dm"'),H=b):(m.log("Config",'Got v1st from backend, v1st_dm created because 3rd party cookie not allowed and 1st party cookie "v1st_dm" does not exist'),
H=B.v1st,L&&N("v1st_dm",H,33696E3))},Na="xbzwps xbzwyj xkb83k x5xhrd x2k4l07 xgphb5 x2k4kr6 x2k4l64 x1fv3qc x1uzrwn".split(" "),oa={inherit:"","16:9":"56.25%","4:3":"75%","1:1":"100%","3:4":"133.3%","9:16":"177.7%"},pa={SMALL:480,MEDIUM:1800,LARGE:2160},Oa="fit fill fillLeft fillRight fillTop fillBottom".split(" "),Z=function(a,b){let c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};const d=Object.prototype.hasOwnProperty.call(oa,b)?b:"16:9",{id:f,iframe:h,rootNode:g,stateFromPES:p}=a._do_not_use_d4e7ed1124e1417cdb42;
Object.assign(g.style,{background:"#0d0d0d",height:"inherit"===d?"100%":"",paddingBottom:oa[d],position:"relative",width:"inherit"===d?"100%":""});Object.assign(h,{height:"100%",width:"100%"});p.playerAspectRatio=d;c.withPesEvent&&K(t.PUBLIC.PLAYER_ASPECTRATIOCHANGE,{id:f,aspectRatio:d})},aa=function(a,b){let c=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};const d=Oa.includes(b)?b:"fit",{id:f,stateFromPES:h}=a._do_not_use_d4e7ed1124e1417cdb42;h.playerScaleMode=d;c.withPesEvent&&K(t.PUBLIC.PLAYER_SCALEMODECHANGE,
{id:f,scaleMode:d})},qa=()=>{const a=window.navigator.connection;return a&&a.effectiveType?a.effectiveType:null},R=a=>{const b={};Object.keys(a).forEach(function(c){const d=a[c];if(void 0!==d&&null!==d&&""!==d){if(null===d)var f=!1;else"object"!==typeof d?f=!1:(f=Object.getPrototypeOf(d),f=f===Object.prototype||null===f);b[c]=f?R(d):d}});return b},Pa=()=>{const a=window.performance.getEntriesByType("resource").find(c=>c.name===document.currentScript.src),b=function(c){let d=1<arguments.length&&void 0!==
arguments[1]?arguments[1]:6E3;return"number"!==typeof c||Number.isNaN(c)||0>c?null:c>d?d:Math.round(c)};return a?{pes_res:{start_time:b(a.startTime,3E4)},pes_custom:{script_request:b(a.requestStart-a.startTime),script_response_start:b(a.responseStart-a.startTime),script_response_end:b(a.responseEnd-a.startTime)}}:null},{udger:{browserOsFamily:ra,browserOsName:sa,browserUaFamily:ta,browserUaName:ua,browserUaVersion:Qa,deviceType:va},geoip:{visitorAsNumber:wa,visitorCity:Ra,visitorContinent:xa,visitorCountry:ya,
visitorRegion:za},player:I,playerEnv:Sa,trafficSegment:ba}=B,Ta=a=>{a={channel:"player",edward:"1.1",sent_ts:Date.now(),events:a.map(R),stack_ctx:{player_stack:"noworker"}};window.fetch("https://pebed.dm-event.net",{method:"POST",body:JSON.stringify(a)})},Aa=async a=>{let {name:b,emptyPlayer:c,pesUUID:d,pesIframeIndex:f,pesIntegrationType:h}=a;if(V("PV5_WATCHTOWER")){a=Date.now();var {pesLastEventTs:g}=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42;g={name:b,version:"1.0",data:{browser:{effective_connection_type:qa(),
os_family:ra,os_name:sa,ua_family:ta,ua_name:ua,user_agent:window.navigator.userAgent},created_ts:a,device:{type:va,height:window.screen.height,width:window.screen.width},player:{embedder:document.location.href,embedder_hostname:document.location.hostname,pes_uuid:d,pes_iframe_index:f,pes_integration_type:h,is_empty:c,pubtool:"pes",version:"v-0.0.3619-rc1",settings:W(I,"isTrackable")},timestamp:{created_event:a,delta_previous_event:g?a-g:0},visitor:{as_number:wa,city:Ra,continent:xa,country:ya,id:H,
onsite:A(),referer:document.referer,region:za,timezone_offset:-6E4*(new Date).getTimezoneOffset(),traffic_segment:ba}}};I.ownerId&&(g.data.publisher={xid:I.ownerId});window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.pesLastEventTs=a;a={channel:"player",edward:"1.1",events:[R(g)],sent_ts:Date.now()};try{const p=await window.fetch("https://pebed.dm-event.net",{method:"POST",body:JSON.stringify(a),headers:{"content-type":"text/plain; charset=UTF-8"}});200===p.status?m.log("Watchtower",b,"sent",a.events[0]):
m.error("Watchtower",b,"failed",p.status,a.events[0])}catch(p){m.error("Watchtower",b,"failed",p.message,a.events[0])}}},Ua={initialize:a=>{const {id:b,observer:c,rootNode:d,settings:f,stateFromPES:h}=a._do_not_use_d4e7ed1124e1417cdb42,g={};a._do_not_use_d4e7ed1124e1417cdb42.removeAllListeners=C(a,t.PRIVATE.ALL,e=>{let {id:l,event:k,fullscreen:n,mode:u,playerHeavyAdsInterventionReports:v,playerHeavyAdsEvents:F}=e;[t.PRIVATE.PLAYER_FULLSCREENCHANGE,t.PRIVATE.PLAYER_NATIVEPIPCHANGE].includes(k)&&(e=
k===t.PRIVATE.PLAYER_FULLSCREENCHANGE?n?"fullscreen":"inline":"inline"===u?"inline":"nativePip",h.playerPresentationMode=e,K(t.PUBLIC.PLAYER_PRESENTATIONMODECHANGE,{id:l,playerPresentationMode:e}));g[k]&&X(k)&&(k===t.PUBLIC.PLAYER_HEAVYADSINTERVENTION?(g[k].forEach(w=>{({cb:w}=w);w({playerHeavyAdsInterventionReports:v})}),m.log("Heavy Ads","Received reports",v),0<F.length&&(m.log("Heavy Ads","Received events",F),Ta(F))):a.getState().then(w=>{g[k].slice().forEach(y=>{({cb:y}=y);y(w)})}))});const p=
e=>{const l=C(a,t.PRIVATE.PLAYER_STATE,k=>{Object.assign(k,h);e(k)});r(a,q.STATE);return l};a.pause=()=>r(a,q.PAUSE);a.play=()=>r(a,q.PLAY);a.seek=e=>r(a,q.SEEK,e);a.setCustomRecommendations=e=>{if(f.enableCustomRecommendations)return e=e.filter(l=>"string"===typeof l&&l.match(/^x[a-zA-Z0-9-_]+$/)),30<e.length&&(console.warn("Custom recommendations are restricted to 30 videos, excess videos will be ignored"),e=e.slice(0,30)),r(a,q.CUSTOM_RECOMMENDATIONS,e);console.warn("Custom recommendations are disabled for that player")};
a.setMute=e=>r(a,q.MUTED,e);a.setQuality=e=>r(a,q.QUALITY,e);a.setSubtitles=e=>r(a,q.SUBTITLES,e);a.setVolume=e=>r(a,q.VOLUME,e);a.setFullscreen=e=>r(a,q.FULLSCREEN,e);a.setControls=()=>{console.warn("The setControls method has been deprecated. Please check https://developers.dailymotion.com/player/#changelog for more details")};a.setCustomConfig=e=>{r(a,q.CUSTOMCONFIG,e)};a.setLoop=e=>{r(a,q.LOOP,e)};a.setPlaybackSpeed=e=>{r(a,q.SPEED,e)};a.setAspectRatio=e=>{Z(a,e,{withPesEvent:!0})};a.setScaleMode=
e=>{r(a,q.SCALE,e);aa(a,e,{withPesEvent:!0})};a.loadContent=e=>{let {video:l,playlist:k,startTime:n}=e;m.log("API","player.loadContent(), with params:",{video:l,playlist:k,startTime:n});e="on"===f.autostart||"firstTimeViewable"===f.autostart&&c.wasViewableAtLeastOnce;if(A()){const u=window.location.href;m.log("API","sendCommandToPlayer(COMMANDS.NOTIFY_EMBEDDER_URL_CHANGED), with url:",u);r(a,q.NOTIFY_EMBEDDER_URL_CHANGED,u)}r(a,q.LOAD,l,{playlist:k,start:n,autoplay:e})};a.updateParams=e=>{void 0!==
e.enableControls&&console.warn("The enableControls parameter from updateParams method has been deprecated. Please check https://developers.dailymotion.com/player/#changelog for more details");void 0!==e.aspectRatio&&Z(a,e.aspectRatio,{withPesEvent:!0});void 0!==e.scaleMode&&aa(a,e.scaleMode,{withPesEvent:!0});r(a,q.UPDATE_PARAMS,e)};a.on=function(e,l){let {once:k=!1}=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{};if(void 0!==e)if("string"===typeof e&&X(e))if("function"!==typeof l)console.warn(`The specified callback should be a function, received ${l}`);
else if(g[e]||(g[e]=[]),g[e].find(v=>{({originalCb:v}=v);return v===l}))console.warn(`Callback duplication detected for ${e}`);else{var n=l;k&&(l=function(){u();n(...arguments)});var u=()=>{g[e]&&(g[e]=g[e].filter(v=>v.originalCb!==n))};g[e].push({originalCb:n,cb:l});return u}else console.warn(`Unknown event, received ${e}`)};a.off=(e,l)=>{void 0!==e&&("string"===typeof e&&X(e)?g[e]?void 0===l?delete g[e]:"function"!==typeof l?console.warn(`The specified callback should be a function, received ${l}`):
g[e]=g[e].filter(k=>k.originalCb!==l):console.warn(`No listener on ${e} to remove`):console.warn(`Unknown event, received ${e}`))};a.getState=()=>new Promise((e,l)=>{const k=C(a,t.PUBLIC.PLAYER_HEAVYADSINTERVENTION,()=>{n();k();l();console.warn(`player.getState() rejected : player ${b} has been destroyed by Heavy Ads`)}),n=p(u=>{n();k();e(u)})});a.getRootNode=()=>d;a.getSettings=()=>W(f,"isPublic");A()&&(a.setControlsForNeon=e=>{r(a,q.CONTROLS,e)})}},ca=!1;class Va{constructor(a){let {embedIndex:b,
emptyPlayer:c,iframe:d,iframeId:f,observer:h,placeholderNode:g,rootNode:p,settings:e,spinner:l}=a;a=window.innerWidth<=pa.SMALL?"smallViewport":"largeViewport";let k="off"===e.pip?"disabled":"enabled";this.hasReceivedVideoChange=this.isEmpty=this.apiReadyReceived=!1;this._do_not_use_d4e7ed1124e1417cdb42={id:f,iframe:d,index:b,initialized:!1,observer:h,placeholderNode:g,rootNode:p,settings:e,spinner:l,stateFromPES:{playerAspectRatio:null,playerIsViewable:null,playerPip:null,playerPipDisplay:a,playerPipIsExpanded:!1,
playerPipStatus:k,playerPresentationMode:"inline",playerScaleMode:null},viewportResizeListener:null};h.init(d);this.isEmpty=c;Z(this,e.aspectRatio);aa(this,e.scaleMode);if(!Ja()){let u=C(this,t.PRIVATE.WRITE_UID,()=>{var v;!1!==(null===(v=B.player)||void 0===v?void 0:v.hasAds)&&L&&N("uid_dm",Y,33696E3);u()})}this.apiReadyReceived=new Promise(u=>{let v=C(this,t.PRIVATE.PLAYER_APIREADY,()=>{d.removeAttribute("name");l&&(d.style.opacity=1,l.remove());v();u()})});let n=C(this,t.PRIVATE.DISPLAY_POSTER_SOONER,
()=>{d.style.opacity=1;l.remove();n()});Ua.initialize(this);"off"===e.pip?ca=Promise.resolve():(window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.playerSelectedForPip?console.warn(`[${e.id}] ${"PIP is already enabled with another configuration"}`):window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.playerSelectedForPip=this,ca=window._dmDynamicImportPolyfill("pes.pip.8d5ee5d5.js"))}initialize(){let {initialized:a}=this._do_not_use_d4e7ed1124e1417cdb42;if(a)return a;let {settings:{autostart:b,pip:c},
id:d,iframe:f,observer:h,rootNode:g}=this._do_not_use_d4e7ed1124e1417cdb42;h.earlyObserve(g);a=(async()=>{await Promise.all([ca,this.apiReadyReceived]);h.unobserve(g);C(this,t.PUBLIC.PLAYER_VIDEOCHANGE,p=>{({title:p}=p);f.setAttribute("title",`Dailymotion video player - ${p.replace(/&/g,"&amp;").replace(/"/g,"&quot;")}`);this.isEmpty&&!this.hasReceivedVideoChange&&(h.unobserve(g),h.observe(g));this.hasReceivedVideoChange=!0});"off"!==c&&(window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.playerSelectedForPip===
this&&window.dailymotion.pipResume(),r(this,q.INIT_PIP_IFRAME_CHUNK));Wa();"firstTimeViewable"===b&&Xa(this);Ya(this);m.log("Player",`${d} fully initialized`);h.observe(g);return this})();return this._do_not_use_d4e7ed1124e1417cdb42.initialized=a}destroy(){let {id:a,observer:b,placeholderNode:c,removeAllListeners:d,rootNode:f,viewportResizeListener:h}=this._do_not_use_d4e7ed1124e1417cdb42;b.unobserve(f);d();Za(this);f.parentNode.replaceChild(c,f);this===window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.playerSelectedForPip&&
(window.dailymotion.pipClose(),window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.playerSelectedForPip=null);window.removeEventListener("resize",h);delete window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.players[a]}isEligibleForPipDisplay(a){let {settings:{pip:b}}=this._do_not_use_d4e7ed1124e1417cdb42;return"off"===b?{status:!1,reason:"PIP is OFF"}:this.isEmpty&&!this.hasReceivedVideoChange?{status:!1,reason:"empty embed without videochange event"}:a?{status:!0,reason:"PIP is ON and was viewable at least once"}:
{status:"instant"===b,reason:"instant"===b?"PIP is INSTANT":"was not viewable at least once"}}}let Xa=a=>{const b=C(a,t.PUBLIC.PLAYER_VIEWABILITYCHANGE,c=>{let {viewable:d,wasViewableAtLeastOnce:f}=c;a&&(d||a.isEligibleForPipDisplay(f).status)&&(b(),a.play())})},Ya=a=>{a._do_not_use_d4e7ed1124e1417cdb42.viewportResizeListener=()=>{r(a,q.VIEWPORT_RESIZE,{width:window.innerWidth,height:window.innerHeight})};window.addEventListener("resize",a._do_not_use_d4e7ed1124e1417cdb42.viewportResizeListener)},
Wa=()=>{ma(t.PUBLIC.PLAYER_VIEWABILITYCHANGE,a=>{let {viewable:b,id:c}=a;if(a=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.players[c])a._do_not_use_d4e7ed1124e1417cdb42.stateFromPES.playerIsViewable=b,r(a,q.PLAYER_VISIBILITY,b)})},Za=a=>{const b=c=>{console.warn(`Invalid call to player.${c}() : player ${a._do_not_use_d4e7ed1124e1417cdb42.id} has been destroyed`)};Object.keys(a).forEach(c=>{"function"===typeof a[c]&&(a[c]=()=>{b(c)})});Object.getOwnPropertyNames(Object.getPrototypeOf(a)).forEach(c=>
{"constructor"!==c&&"function"===typeof a[c]&&(a[c]=()=>{b(c)})})},Ba=[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,1],ab=(a,b,c,d)=>{if(!0===b)return m.log("Observer","No header overlapping ! Reason: IO isVisible is true"),{status:!1,marginTop:null};const {x:f,y:h,width:g,height:p}=a.getBoundingClientRect();if(0<=h)return m.log("Observer",`Overlapping detection canceled ! Reason : Player is not about to pass above the fold, y:${h}`),{status:!1,marginTop:null};a=document.elementFromPoint(f+Math.round(.5*g),h+Math.round(p*
(1-d)));if(!a)return m.log("Observer","No header overlapping ! Reason: No overlapping element"),{status:!1,marginTop:null};if(c.isSameNode(a))return m.log("Observer","No header overlapping ! Reason: Overlapping element is the same as the player iframe"),{status:!1,marginTop:null};c=$a(a);if(!c)return m.log("Observer",'No header overlapping ! Reason: Overlapping element or ancestors are not in "fixed" position'),{status:!1,marginTop:null};const {x:e,y:l,width:k,height:n}=c.getBoundingClientRect();
m.log("Observer",`Overlapping header detection data :
        - IO isVisible : ${b}
        - targetX : ${f}
        - targetY : ${h}
        - targetWidth : ${g}
        - targetHeight : ${p}
        - fixedElementX : ${e}
        - fixedElementY: ${l}
        - fixedElementWidth: ${k}
        - fixedElementHeight: ${n}
        - fixed element:`,c,"\n        - overlapping element:",a);if(0!==l)return m.log("Observer","No header overlapping ! Reason: Overlapping element Y position is not 0"),{status:!1,marginTop:null};if(!(e<=f&&k>=g))return m.log("Observer","No header overlapping ! Reason: Overlapping element is not fully covering the player width"),{status:!1,marginTop:null};m.log("Observer","Fixed header is overlapping player iframe");return{status:!0,marginTop:n}},$a=a=>{try{for(;a;){const b=window.getComputedStyle(a).getPropertyValue("position").toLowerCase();
if("fixed"===b||"sticky"===b)return a;a=a.parentNode instanceof HTMLElement&&"BODY"!==a.tagName?a.parentNode:null}return null}catch(b){return null}};class bb{constructor(){this.uiActionOrigin=this.intersectionObserver=null;this.earlyObserverMode=this.wasViewableAtLeastOnce=!1;this.playerIframe=null;this.hasCompletedHeaderDetection=!1;this.intersectionObserver=new window.IntersectionObserver(this.intersectionObserverCallback.bind(this),{threshold:Ba})}init(a){this.playerIframe=a;m.log("Observer","Observer initialized with header detection")}intersectionObserverCallback(a){a.forEach(b=>
{let {intersectionRatio:c,target:d,isVisible:f}=b;if((b=.5<=c)&&!this.hasCompletedHeaderDetection&&0>=d.getBoundingClientRect().y){let {status:h,marginTop:g}=ab(d,f,this.playerIframe,.5);h&&(this.hasCompletedHeaderDetection=!0,b=!1,this.intersectionObserver.disconnect(),this.intersectionObserver=null,m.log("Observer","Defining new observer with root marginTop",g),this.intersectionObserver=new window.IntersectionObserver(this.intersectionObserverCallback.bind(this),{rootMargin:`-${g}px 0px 0px 0px`,
threshold:Ba}),this.intersectionObserver.observe(d))}b&&!this.wasViewableAtLeastOnce&&(m.log("Observer","Player iframe was viewable at least once"),this.wasViewableAtLeastOnce=!0);this.earlyObserverMode||K(t.PUBLIC.PLAYER_VIEWABILITYCHANGE,{id:d.id,viewable:b,wasViewableAtLeastOnce:this.wasViewableAtLeastOnce,...(this.uiActionOrigin?{uiActionOrigin:this.uiActionOrigin}:{})});this.uiActionOrigin=null})}observe(a){var b;null===(b=this.intersectionObserver)||void 0===b?void 0:b.observe(a)}earlyObserve(a){var b;
m.log("Observer","Early intersection observer has started");this.earlyObserverMode=!0;null===(b=this.intersectionObserver)||void 0===b?void 0:b.observe(a)}unobserve(a){var b;this.earlyObserverMode=!1;null===(b=this.intersectionObserver)||void 0===b?void 0:b.unobserve(a)}disconnect(){var a;null===(a=this.intersectionObserver)||void 0===a?void 0:a.disconnect()}setUIActionOrigin(a){this.uiActionOrigin=a}}let Ca={create:async function(a,b,c,d){var f;let {videoId:h,playlistId:g,playerId:p,params:e,settings:l,
referrerPolicy:k}=4<arguments.length&&void 0!==arguments[4]?arguments[4]:{};if("embed"!==d||null!==(f=document.body)&&void 0!==f&&f.contains(a)){var n=a.id||`dailymotion-instance-${P()}`,u=a.parentNode;f=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.iframeIndex++;var v=!h&&!g,F=new bb,w=ja(e),y=ja(l),da=`pes${(null===w||void 0===w?0:w.dmPubtool)?`-${w.dmPubtool}`:""}`,z=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.settings,x=z[p];if(void 0===x)try{x=await (await window.fetch(`${J()?"https://geo2.dailymotion.com":
"https://geo.dailymotion.com"}/player/${p}.json`,{method:"GET"})).json(),m.log("Player settings",x),"server_error"===x.status&&console.warn(`${"An unexpected error occured when retrieving player configuration"} : ${x.id}`),"not_found"===x.status&&console.warn(`${"The player configuration ID has not been found"} : ${x.id}`),"deleted"===x.status&&console.warn(`${"The player configuration ID has been deleted"} : ${x.id}`),z[x.id]=x}catch(S){console.error("Settings fetch error: ",S);return}x=Fa(x,y);
w=cb(h,g,p,w,k);z=document.createElement("div");z.id=n;z.classList.add("dailymotion-player-root");z.classList.add(`dailymotion-player-${p}`);y=document.createElement("div");y.className="dailymotion-player-wrapper";Object.assign(y.style,{height:"100%",overflow:"hidden",position:"absolute",width:"100%",margin:"0.00001px"});var D,G=document.createElement("div"),E=640<((null===u||void 0===u?void 0:null===(D=u.getBoundingClientRect())||void 0===D?void 0:D.width)||0)?"48":"40";Object.assign(G.style,{height:`${E}px`,
left:"50%",position:"absolute",top:"50%",transform:"translate3d(-50%, -50%, 0)",width:`${E}px`});G.innerHTML=`<svg
      xmlns="http://www.w3.org/2000/svg"
      aria-hidden="true"
      height="${E}"
      viewBox="0 0 50 50"
      width="${E}"
    >
      <circle
        cx="25"
        cy="25"
        fill="none"
        r="20"
        stroke="#fff"
        stroke-dasharray="125.6, 125.6"
        stroke-width="4"
        transform="rotate(-90 25 25)"
      />
    </svg>`;G.querySelector("circle").animate([{strokeDashoffset:"125.6"},{strokeDashoffset:"0"},{strokeDashoffset:"-125.6"}],{duration:1200,iterations:Infinity});D=new Va({embedIndex:b,emptyPlayer:v,iframe:w,iframeId:n,observer:F,placeholderNode:a,rootNode:z,settings:x,spinner:G});window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.players[n]=D;y.appendChild(G);z.appendChild(y);u.replaceChild(z,a);n=await db({embedIndex:b,iframeId:n,pesIframeIndex:f,pesIntegrationType:d,pesUUID:c,pubtool:da,settings:x});
w.name=encodeURIComponent(n);y.appendChild(w);Aa({name:"vital_pes_iframe_start",emptyPlayer:v,pesIframeIndex:f,pesIntegrationType:d,pesUUID:c});return D}console.warn("The Player Embed Script can't be injected in document head, please use Library Script instead. More details: https://developers.dailymotion.com/guides/getting-started-with-web-sdk/#player-library-script")}},cb=function(a,b,c){let d=3<arguments.length&&void 0!==arguments[3]?arguments[3]:{},f=4<arguments.length?arguments[4]:void 0;const h=
document.createElement("iframe"),g="default"!==c?`/player/${c}.html`:"/player.html",p={...(a&&{video:a}),...(b&&{playlist:b})};Object.keys(d).filter(k=>!p[k]).forEach(k=>{d[k]&&"object"===typeof d[k]?Object.keys(d[k]).forEach(n=>{p[`${k}[${n}]`]=encodeURIComponent(d[k][n])}):p[k]=encodeURIComponent(d[k])});var e=window.location.href.match(/dmDevBackendEnv=[-_a-zA-Z0-9]+/);null!==e&&([,e]=e[0].split("="),p.dmDevBackendEnv=e);e=Object.keys(p).map(k=>`${k}=${p[k]}`).join("&");const l=["autoplay","fullscreen",
"picture-in-picture",...(window.navigator.canShare?["web-share"]:[])];Object.assign(h,{allow:l.join("; "),className:"dailymotion-player",frameBorder:0,src:`${J()?"https://geo2.dailymotion.com":"https://geo.dailymotion.com"}${g}?${e}`,title:"Dailymotion video player",...(f&&{referrerPolicy:f})});h.style.opacity=0;return h},db=async a=>{let {embedIndex:b,iframeId:c,pesIframeIndex:d,pesIntegrationType:f,pesUUID:h,pubtool:g,settings:p}=a;const {trafficSegment:e,playerGatekeepers:l,player:k}=B,{location:n,
origin:u,innerWidth:v,innerHeight:F}=window,{hasOverride:w,enableReceiveUrlLocation:y,enableSharingUrlLocation:da,enableContextualContent:z}=p,{pesLastEventTs:x,neonTrackingData:D}=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42;a={width:v,height:F};const G=w?p:void 0;let E=null;if(y||da)n.hostname?E=n.href:n.ancestorOrigins&&(E=n.ancestorOrigins[0]);let S=null;try{S=(new URL(document.referrer)).origin}catch(T){}const eb=z?await Ia():null,[fb]=await Promise.all([(async()=>{if(!Na.includes(null===
k||void 0===k?void 0:k.ownerId))return Promise.resolve(null);try{await window._dmDynamicImportPolyfill("pes.liveramp.f3a29bf0.js");const T=await window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.getLiverampEnvelope();return Promise.resolve(T)}catch(T){return Promise.reject(T)}})(),Ea()]);N("_TEST_","1");L="1"===O("_TEST_");N("_TEST_",null,0);A()?Q=L:"undefined"!==typeof window.dmCookie3rdPartyAllowed&&(Q=window.dmCookie3rdPartyAllowed,delete window.dmCookie3rdPartyAllowed);Ma();Ka();return JSON.stringify({dmInternalData:{contextualPageData:eb,
cookies1stPartyAvailable:L,cookies3rdPartyAvailable:Q,embedder:E,embedIndex:b,forcedSettings:G,gatekeepers:l,iframeId:c,initialViewportSize:a,liverampEnvelope:fb,logger:ea(),neonTrackingData:D,pesIframeIndex:d,pesIntegrationType:f,pesLastEventTs:x,pesPlayerVersion:"v-0.0.3619-rc1",pesUUID:h,pubtool:g,referer:S,targetOrigin:u,ts:e,uid:Y,v1st:H}})},M=()=>{console.warn("PIP is disabled in the configuration")},gb=a=>{m.log("API","dailymotion.forwardNeonTrackingData(data), with data:",a);const {players:b}=
window.dailymotion._do_not_use_d4e7ed1124e1417cdb42,c=Object.keys(b);0===c.length?window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.neonTrackingData=a:r(b[c[0]],q.UPDATE_NEON_TRACKING_DATA,a)},hb=()=>{const {udger:{browserOsFamily:a,browserOsName:b,browserUaFamily:c,browserUaName:d,browserUaVersion:f}={}}=B;return{osFamily:a,osName:b,uaFamily:c,uaName:d,uaVersion:f}},ib={createPlayer:async function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:{};const {settings:c,embedScriptIndex:d,
pesUUID:f}=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42,h=document.querySelector(`#${a}`);if(!h)return Promise.reject(Error(`${"DOM element ID not found"} : #${a}`));if(h.classList.contains("dailymotion-player-wrapper"))return Promise.reject(Error(`${"A player instance is already attached to this DOM element"} : #${a}`));if(b&&"object"!==typeof b)return Promise.reject(Error("Player options invalid, please use an object"));b.player||(1===Object.keys(c).length?b.player=Object.keys(c)[0]:(1<Object.keys(c).length&&
console.warn("Several player configurations are imported, please specify a player configuration ID"),b.player="default"));b=await Ca.create(h,d,f,"lib",{videoId:b.video,playlistId:b.playlist,playerId:b.player,params:b.params,settings:b.settings,referrerPolicy:b.referrerPolicy});return null===b||void 0===b?void 0:b.initialize()},events:t.PUBLIC,getAllPlayers:()=>{const {players:a}=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42,b=[];if(0===Object.keys(a).length)return Error("No player found in the page");
Object.values(a).forEach(c=>b.push(null===c||void 0===c?void 0:c.initialize()));return b},getPlayer:a=>{const {players:b}=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42,c=b[a];if(0===Object.keys(b).length)return Promise.reject(Error("No player found in the page"));if(void 0===a){var d;return 1<Object.keys(b).length?Promise.reject(Error("There are multiple players in the page, please specify an ID")):null===(d=Object.values(b)[0])||void 0===d?void 0:d.initialize()}return void 0===c?Promise.reject(Error(`${"Player ID not found"} : #${a}`)):
null===c||void 0===c?void 0:c.initialize()},pipClose:M,pipCollapse:M,pipExpand:M,pipRepaint:M,pipResume:M,...(A()&&{forwardNeonTrackingData:gb,getEnvironmentInfo:hb}),_do_not_use_d4e7ed1124e1417cdb42:{api:null,embedScriptIndex:1,iframeIndex:1,neonTrackingData:null,pesUUID:null,players:{},playerSelectedForPip:null,screenId:P(),settings:{}}};window._dmDynamicImportPolyfill=a=>{const b=`pes-${a}`;var c=document.querySelector(`script[id="${b}"]`);if(c)return ha(c);c=document.createElement("script");c.src=
`${"https://static1.dmcdn.net/playerv5"}/${a}`;c.id=b;a=ha(c);document.body.appendChild(c);return a};let U=B.player;if(!U)throw Error("Backend settings not set");let {id:jb,status:kb}=U;(async a=>{var b=document.currentScript;let {dataset:{video:c,playlist:d,params:f,settings:h},referrerPolicy:g,src:p}=b;var e=!c&&!d;let l=p.match(/\/libs\//)?"lib":"embed",k=!!p.match(/geo2/)||!1,n=P();null!==(a=window.dailymotion)&&void 0!==a&&a.createPlayer||(window.dailymotion={...window.dailymotion,...ib});Aa({name:"vital_pes_enter",
emptyPlayer:"lib"===l?null:e,pesIntegrationType:l,pesUUID:n});window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.pesUUID=n;window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.isGeo2=k;m.log("PES UUID",n);"ok"===kb&&(window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.settings[U.id]=U);"function"===typeof window.dailymotion.onScriptLoaded&&(window.dailymotion.onScriptLoaded(),delete window.dailymotion.onScriptLoaded);"lib"===l?m.log("Library script loaded"):(a=window.dailymotion._do_not_use_d4e7ed1124e1417cdb42.embedScriptIndex++,
m.log("Embed script loaded",`Index ${a}`),e={name:"life_cycle.embedStart",version:"1.0",data:{context:{visitor_group:Math.ceil(ba/1E4)},created_ts:Date.now(),empty_player:e,info:{browser:{effective_connection_type:qa(),os_family:ra,os_name:sa,ua_family:ta,ua_name:ua,ua_version:Qa,user_agent:window.navigator.userAgent},device:{type:va,width:window.innerWidth,height:window.innerHeight},player:{config:W(I,"isTrackable"),embedder:document.location.href,embedder_hostname:document.location.hostname,env:Sa,
is_geo:!0,is_geo2:k,secure:!0,version:"v-0.0.3619-rc1"},visitor:{as_number:wa,continent:xa,country:ya,onsite:A(),referer:document.referer,region:za,timezone_offset:-6E4*(new Date).getTimezoneOffset(),traffic_segment:ba}},perf:Pa(),settings:{embed_index:a,pubtool:"pes"}}},I.ownerId&&(e.data.info.publisher={type:"player",xid:I.ownerId}),e={channel:"player",edward:"1.1",sent_ts:Date.now(),events:[R(e)],stack_ctx:{player_stack:"noworker"}},window.fetch("https://pebed.dm-event.net",{method:"POST",body:JSON.stringify(e)}),
b=await Ca.create(b,a,n,"embed",{videoId:c,playlistId:d,playerId:jb,params:f,settings:h,referrerPolicy:g}),null===b||void 0===b?void 0:b.initialize())})();return{B:pa,C:q,E:300,a:t,b:ka,c:r,d:ma,l:m,s:K}}()
// pv5template